version: 0.0
os: linux
runas: root

files:
  - source: /
    destination: /home/ubuntu/project-space/*
    overwrite: true
    timeout: 500
    a
hooks:

  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root


  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
