version: 0.2

run-as: root
env:
  secrets-manager:
    MONGODB_URL: "/mongodb/kunjan-mongodb-url:kunjan-mongodb-url"

phases:
   pre_build:
     commands:
      - npm install pm2 -g
      - echo "kunjan-mongodb-url=$kunjan-mongodb-url" > .env

   build:
     commands:
        - echo "build application"
        

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
