version: 0.2

run-as: root
env:
  secrets-manager:
    MONGODB_URL: "/mongodb/kunjan-mongodb-url:kunjan-mongodb-url"

phases:
   pre_build:
     commands:
      - echo "MONGODB_URI=$MONGODB_URL" > .env
      - npm install
      
   build:
     commands: 
      - echo "build stage"
      
artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
