version: 0.2

run-as: root
env:
  secrets-manager:
    MONGODB_URL: "/mongodb/kunjan-mongodb-url:kunjan-mongodb-url"

phases:
   pre_build:
     commands:
      - npm install
      - npm install --save dotenv
      - echo "kunjan-mongodb-url=$kunjan-mongodb-url" > .env
      
      - sed -i "s|mongodb://localhost/conduit|$kunjan-mongodb-url|" app.js
      - cat app.js

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
