version: 0.2

run-as: root
env:
  secrets-manager:
    MONGODB_URL: "/mongodb/kunjan-mongodb-url:kunjan-mongodb-url"

phases:
   pre_build:
     commands:
      - npm install
      - echo "MONGODB_URI=$kunjan-mongodb-url" > .env
   build:
      commands:
       - cat app.js

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
